# Generated by Django 5.0 on 2023-12-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('data_proxima_manutencao', models.DateField(verbose_name='Próxima Manutenção')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('num_hab', models.AutoField(primary_key=True, serialize=False)),
                ('estado_hab', models.CharField(max_length=25, verbose_name='Estado da Habilitação')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('end', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('nome', models.CharField(max_length=200)),
                ('ar_condicionado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de Veículo',
                'verbose_name_plural': 'Tipos de Veículos',
            },
        ),
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.veiculo')),
                ('num_portas', models.IntegerField(verbose_name='Número de Portas')),
                ('dir_hidraulica', models.BooleanField(default=False, verbose_name='Direção Hidráulica')),
                ('cambio_auto', models.BooleanField(default=False, verbose_name='Câmbio Automático')),
            ],
        ),
        migrations.CreateModel(
            name='Onibus',
            fields=[
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.veiculo')),
                ('num_passageiros', models.IntegerField(verbose_name='Número de Passageiros')),
                ('leito', models.BooleanField(default=False)),
                ('sanitario', models.BooleanField(default=False, verbose_name='Sanitário')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data da Locação')),
                ('duracao', models.IntegerField(verbose_name='Duração do contrato(Em dias)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoveiculo'),
        ),
    ]
